#!/bin/bash

# Kernel framework.

# linux version
# MY_DIR="$(dirname $(readlink -e $0))"
# portable solution
MY_DIR="$(cd $(dirname $0); pwd -P)"

TOOLS_DIR="$MY_DIR/src"

cmd=$1; shift
if [[ -e ${TOOLS_DIR}/${cmd}.sh ]]
then
    echo "No command ${cmd} found."
    exit 1
fi

"${TOOLS_DIR}/${cmd}.sh" $*
