#!/bin/bash

# Kernel framework.

MY_DIR="$(cd $(dirname $0); pwd)"

TOOLS_DIR="$MY_DIR/src"

cmd=$1; shift
if [[ ! -e ${TOOLS_DIR}/${cmd}.sh ]]
then
    echo "No command ${cmd} found."
    exit 1
fi

bash "${TOOLS_DIR}/${cmd}.sh" $*
